from typing import Dict, Set, Any

base_id = 1

magic_items: Dict[str, str] = {
    "Arcane": "Attack Magics",
    "Ice": "Attack Magics",
    "Fire": "Attack Magics",
    "Thunder": "Attack Magics",
    "Wind": "Double Jump",
    "Mana Absorption": "Counter",
}

useful_items: Dict[str, str] = {
    "Progressive Bag Upgrade": "Bag Upgrade",
}

boss_souls: Dict[str, str] = {
    "Specter Armor Soul": "Boss Souls",
    "Tania Soul": "Boss Souls",
    "Monica Soul": "Boss Souls",
    "Enraged Armor Soul": "Boss Souls",
    "Vanessa Soul": "Boss Souls",
    "Vanessa V2 Soul": "Boss Souls",
}

boss_tokens: Dict[str, str] = {
    "Specter Armor Token": "Boss Tokens",
    "Tania Token": "Boss Tokens",
    "Monica Token": "Boss Tokens",
    "Enraged Armor Token": "Boss Tokens",
    "Vanessa Token": "Boss Tokens",
    "Vanessa V2 Token": "Boss Tokens",
}

filler_crystal_items: Dict[str, str] = {
    "Meager Life Crystal": "Filler",
    "Faint Life Crystal": "Filler",
    "Fair Life Crystal": "Filler",
    "Fine Life Crystal": "Filler",
    "Meager Magic Crystal": "Filler",
    "Faint Magic Crystal": "Filler",
    "Fair Magic Crystal": "Filler",
    "Fine Magic Crystal": "Filler",
    "Faint Defense Crystal": "Filler",
    "Fair Defense Crystal": "Filler",
    "Fine Defense Crystal": "Filler",
    "Faint Arcane Crystal": "Filler",
    "Fair Arcane Crystal": "Filler",
    "Fine Arcane Crystal": "Filler",
    "Faint Holy Crystal": "Filler",
    "Fair Holy Crystal": "Filler",
    "Fine Holy Crystal": "Filler",
}

filler_souls_items: Dict[str, str] = {
    "Souls": "Filler",
    "HP Souls": "Filler",
    "MP Souls": "Filler",
}

trap_items: Dict[str, str] = {
    "Bonk Trap": "Trap",
    "Mana Drain Trap": "Trap",
    "Darkness Trap": "Trap",
    "Shrink Trap": "Trap",
}

lore_items: Dict[str, str] = {
    "1. Crafted Soul Reader": "Lore",
    "2. Stained Ribbon": "Lore",
    "3. Copper Coin": "Lore",
    "4. Unknown House Banner": "Lore",
    "5. Melted Silver Candlestick": "Lore",
    "6. Broken Cross Spear": "Lore",
    "7. Deformed Cavalier Armor": "Lore",
    "8. Hero's Cross Sword": "Lore",
    "9. Giant Axe": "Lore",
    "10. Shield of the Church": "Lore",
    "11. Broken Queen Doll": "Lore",
    "12. Pointy Witch's Hat": "Lore",
    "13. Sleeve Dagger": "Lore",
    "14. Corpse Shroud": "Lore",
    "15. Headcutter Circular Saw": "Lore",
    "16. Test Subject Manacle": "Lore",
    "17. Tattered Maid Outfit": "Lore",
    "18. Soul Doll Remnant": "Lore",
    "19. Knight's Halberd": "Lore",
    "20. Weathered Cloak": "Lore",
    "21. Silver Coin": "Lore",
    "22. Intricate Clock": "Lore",
    "23. Cursed Turquoise Necklace": "Lore",
    "24. Glass Lantern": "Lore",
    "25. Copper Ingot": "Lore",
    "26. Teddy Bear": "Lore",
    "27. Fractured Stone Axe": "Lore",
    "28. Cage": "Lore",
    "29. Slave Branding Iron": "Lore",
    "30. Merchant's Ledger": "Lore",
    "31. Slave Tag": "Lore",
    "32. Slave Collar": "Lore",
    "33. Bestian Palm": "Lore",
    "34. Bestian Ear": "Lore",
    "35. Dwarven Metalwork": "Lore",
    "36. High Elf's Mana Ring": "Lore",
    "37. Forest Elf's Vest": "Lore",
    "38. Dark Elf's Ear Sample": "Lore",
    "39. Dark Elf's Short Bow": "Lore",
    "40. Ogre's Kidney": "Lore",
    "41. Ogre's Eye": "Lore",
    "42. Ogre's Club": "Lore",
    "43. Bloodstained Javelin": "Lore",
    "44. Nomad's Cookware": "Lore",
    "45. Golden Coin": "Lore",
    "46. Tooth Thief's Pouch": "Lore",
    "47. Blood Orc's Skin Sample": "Lore",
    "48. Chief's Skull": "Lore",
    "49. Chief's Skull": "Lore",
    "50. Crafted Soul Injector": "Lore",
    "51. Hero's Insignia": "Lore",
    "52. Mutated Beast Claw": "Lore",
    "53. Ceremonial Sword": "Lore",
    "54. Banner of the Lance Hero": "Lore",
    "55. Banner of the Lionhearted": "Lore",
    "56. Knight Kingdom Crown": "Lore",
    "57. Lady's Feather Hat": "Lore",
    "58. Super Cleanser Soap": "Lore",
    "59. Exquisite Leather Lamp": "Lore",
    "60. Premium Grass Ash": "Lore",
    "61. Knight Kingdom Entry Pass": "Lore",
    "62. Bone Chess Set": "Lore",
    "63. Inquisitor's List": "Lore",
    "64. Envoy's Rune": "Lore",
    "65. Declaration of War": "Lore",
    "66. Attic Key": "Lore",
    "67. Halfling's Forelimb": "Lore",
    "68. Ratian Claw": "Lore",
    "69. Pontiff's Scepter": "Lore",
    "70. Abandoned Rag Doll": "Lore",
    "71. Apocalypse Knight Record": "Lore",
    "72. Apocalypse Knight Shield": "Lore",
    "73. Apocalypse Knight Axe": "Lore",
    "74. Apocalypse Knight Staff": "Lore",
    "75. Apocalypse Knight Bow": "Lore",
    "76. Apocalypse Knight Sword": "Lore",
    "77. The Throne": "Lore",
    "78. Ancient Throne Rune": "Lore",
    "79. Doctor's Mask": "Lore",
    "80. Ceremonial Incense": "Lore",
    "81. Moonlight Blade": "Lore",
    "82. Prostitute's Chiffon": "Lore",
    "83. Castle Blueprint": "Lore",
    "84. Witch Worshipper Puppet": "Lore",
    "85. Polymorphism Scroll": "Lore",
    "86. Missing Person Poster": "Lore",
    "87. Saint's Cane": "Lore",
    "88. Hero Summon Rune": "Lore",
    "89. Bloodstained Key": "Lore",
    "90. Enchanted Shackles": "Lore",
    "91. Gaseous Soul Essence": "Lore",
    "92. Semi-gaseous Soul Essence": "Lore",
    "93. Enchanted Soul Shard": "Lore",
    "94. Knight's Soul Shard": "Lore",
    "95. Refined Soul Shard": "Lore",
    "96. Knight's Soul Shard": "Lore",
    "97. Faithful Soul Shard": "Lore",
    "98. Lost Maiden's Soul Shard": "Lore",
    "99. Child's Soul Shard": "Lore",
    "100. King's Final Honor": "Lore",
    "101. Proud King's Crafted Soul Shard": "Lore",
    "102. Lost Maiden's Crafted Soul Shard": "Lore",
    "103. Loyal Soul Shard": "Lore",
}

barrier_items: Dict[str, str] = {
    "Shrine First Magic Barrier": "Magic Barrier",
    "Shrine Second Magic Barrier": "Magic Barrier",
    "Shrine Meet Cat Magic Barrier": "Magic Barrier",
    "Secret Passage Entrance Magic Barrier": "Magic Barrier",
    "Secret Passage First Fire Barrier": "Magic Barrier",
    "Secret Passage Second Fire Barrier": "Magic Barrier",
    "Defeat Enraged Armor Barrier": "Magic Barrier",
    "Underground Magic Barrier At Maid Enemy": "Magic Barrier",
    "Underground Fire Barrier Magic Barrier": "Magic Barrier",
    "Underground Enemy Magic Barrier": "Magic Barrier",
    "Underground Tania Arena Barrier": "Magic Barrier",
    "Lava Ruins Magic Platforms": "Magic Barrier",
    "Lava Ruins Scissor Enemy Barrier": "Magic Barrier",
    "Lava Ruins Scissor Enemy Lift": "Magic Barrier",
    "Lava Ruins Fire Magic Barrier": "Magic Barrier",
    "Lava Ruins Moving Ring": "Magic Barrier",
    "Lava Ruins Monica Arena Barrier": "Magic Barrier",
    "Dark Tunnel First Magic Barrier": "Magic Barrier",
    "Dark Tunnel Light Switch Barrier": "Magic Barrier",
    "Dark Tunnel Thunder Barrier": "Magic Barrier",
    "Dark Tunnel Floating Platform One": "Magic Barrier",
    "Dark Tunnel Floating Platform Two": "Magic Barrier",
    "Dark Tunnel Floating Platform Three": "Magic Barrier",
    "Spirit Realm Arcane Barrier": "Magic Barrier",
    "Spirit Realm Platform Shortcut": "Magic Barrier",
    "Spirit Realm First Seal Magic Barrier": "Magic Barrier",
    "Spirit Realm Second Seal Magic Barrier": "Magic Barrier",
    "Spirit Realm Elevator": "Magic Barrier",
    "Spirit Realm Teleporter": "Magic Barrier",
    "Spirit Realm Fire Deactivation": "Magic Barrier",
    "Spirit Realm Magic Switch Barrier": "Magic Barrier",
    "Abyss After Giant Maid Barrier": "Magic Barrier",
    "Abyss Underground Trial Magic Switch": "Magic Barrier",
    "Abyss Underground Trial Exit Barrier": "Magic Barrier",
    "Abyss Underground Trial After Scissor Enemy Barrier": "Magic Barrier",
    "Abyss Lava Ruins Trial Magic Switch": "Magic Barrier",
    "Abyss Lava Ruins Trial Lower Lava": "Magic Barrier",
    "Abyss Dark Tunnel Trial Magic Switch": "Magic Barrier",
    "Abyss Dark Tunnel Trial Maid Enemy Barrier": "Magic Barrier",
    "Abyss Lava Ruins Trial Maid Enemy Barrier": "Magic Barrier",
}

gate_items: Dict[str, str] = {
    "Shrine Secret Boss Shortcut Gate": "Metal Gate",
    "Shrine Secret Area Shortcut Gate": "Metal Gate",
    "Shrine Underground Shortcut Gate": "Metal Gate",
    "Secret Passage Dark Tunnel Shortcut Gate": "Metal Gate",
    "Underground Lava Ruins Shortcut Gate": "Metal Gate",
    "Underground Tania Shortcut Gate On Grand Hall Side": "Metal Gate",
    "Underground Tania Shortcut Gate On Tania Side": "Metal Gate",
    "Lava Ruins Fake Floor Shortcut Gate": "Metal Gate",
    "Lava Ruins Monica Shortcut Gate": "Metal Gate",
    "Lava Ruins Monica Warp Gate": "Metal Gate",
    "Dark Tunnel First Gate": "Metal Gate",
    "Spirit Realm Wind Spell Chest Gate": "Metal Gate",
    "Spirit Realm Ice Spell Chest Gate": "Metal Gate",
    "Spirit Realm Statue Shortcut Gate": "Metal Gate",
    "Abyss First Gate": "Metal Gate",
    "Abyss Trap Gates": "Metal Gate",
}

abyss_trial_items: Dict[str, str] = {
    "Abyss Underground Trial Clear": "Abyss Trial Clear",
    "Abyss Lava Ruins Trial Clear": "Abyss Trial Clear",
    "Abyss Dark Tunnel Trial Clear": "Abyss Trial Clear",
}

lwn_items: Dict[str, str] = {
    **magic_items,
    **useful_items,
    **boss_souls,
    **boss_tokens,
    **filler_crystal_items,
    **filler_souls_items,
    **trap_items,
    **lore_items,
    **barrier_items,
    **gate_items,
    **abyss_trial_items,
    "Teleport": "Teleport",
    "Underground Trial Key": "Trial Key",
    "Lava Ruins Trial Key": "Trial Key",
    "Dark Tunnel Trial Key": "Trial Key",
}

item_name_groups = {
    "Attack Magics": magic_items.keys(),
    "Boss Souls": boss_souls.keys(),
    "Boss Tokens": boss_tokens.keys(),
    "Double Jump": {"Wind"},
    "Counter": {"Mana Absorption"},
    "Lore": lore_items.keys(),
    "Magic Barrier": barrier_items.keys(),
    "Metal Gate": gate_items.keys(),
    "Abyss Trial Clear": abyss_trial_items.keys(),
    "Bag Upgrade": {"Progressive Bag Upgrade"},
}

item_name_to_id: Dict[str, int] = {name: base_id + index for index, name in enumerate(sorted(lwn_items))}
